POST http://localhost:8000/funql
content-type: application/json

{
  "wants": {
      "model": "Order",
      "doit":"Delete"
  },
  "details":{
    "set":{
      "_id":"60486c3796114b7583e56d36"
    },
    "get":{
      "name":1
    }
  }
}

