POST http://localhost:8000/funql
content-type: application/json

{
  "wants": {
      "model": "City",
      "doit":"Delete"
  },
  "details":{
    "set":{
      "_id":"604db2e7b794b41279fba06b"
    },
    "get":{}
  }
}