POST http://localhost:8000/funql
content-type: application/json

{
  "wants": {
      "model": "Table",
      "doit": "Adding"
  },
  "details":{
  "set":{
      "tableNo": 1,
      "tableCapacity": 4,
      "reservable": true
    },
    "get":{}
  }
}


//  Testing Func
//  Center
//  Menu
//  Table