POST http://localhost:8000/funql
content-type: application/json

{
  "wants": {
      "model": "Menu",
      "doit":"Delete"
  },
  "details":{
    "set":{
      "_id":"6044713356f2151dd7653e7a"
    },
    "get":{
      "name":1
    }
  }
}

