POST http://localhost:8000/funql
content-type: application/json

//Not Work : Success True But Not Delete
{
  "wants": {
      "model": "Menu",
      "doit":"Delete"
  },
  "details":{
    "set":{
      "_id":"604470e156f2151dd7653e79"
    },
    "get":{
      "name":1
    }
  }
}

