POST http://localhost:8000/funql
content-type: application/json

{
  "wants": {
      "model": "Menu",
      "doit":"Update"
  },
  "details":{
    "set":{
      "_id": "6065c09af0fb76c1b45511b2",
      "name": "Orange juice",
      "menuCategory":{
        "title":"Drinks",
        "dish":{
          "name":"water",
          "price": 5000,
          "photo": "some water photo"
        }
      }
    },
    "get":{}
  }
}