POST http://localhost:8000/funql
content-type: application/json

//Not Work With All Props (Work With Name)

{
  "wants": {
      "model": "Menu",
      "doit":"Update"
  },
  "details":{
    "set":{
      "_id": "6065c09af0fb76c1b45511b2",
      "name": "Orange juice"
    },
    "get":{}
  }
}