POST http://localhost:8000/funql
content-type: application/json

{
  "wants": {
      "model": "Parish",
      "doit":"Delete"
  },
  "details":{
    "set":{
      "_id":"604db30f01732bf64f8399ee"
    },
    "get":{
      "name":1
    }
  }
}

