POST http://localhost:8000/funql
content-type: application/json

//Not Work : Success True But Not Delete
{
  "wants": {
      "model": "Parish",
      "doit":"Delete"
  },
  "details":{
    "set":{
      "_id":"6065c7570a0a3c503c7ef6c9"
    },
    "get":{
      "name":1
    }
  }
}

