POST http://localhost:8000/funql
content-type: application/json

{
  "wants": {
      "model": "User",
      "doit":"Delete"
  },
  "details":{
    "set":{
      "_id":"60544690895e80dc6860ddf2"
    },
    "get":{}
  }
}

