POST http://localhost:8000/funql
content-type: application/json

{
  "wants": {
      "model": "City",
      "doit":"Add"
  },
  "details":{
    "set":{
      "name": "Second City",
      "geometries":[45, 50]
    },
    "get":{}
  }
}