POST http://localhost:8000/funql
content-type: application/json

//Error => return all props 

{
  "wants": {
      "model": "City",
      "doit":"Delete"
  },
  "details":{
    "set":{
      "_id":"606be46bf43fcd55b94c72c1"
    },
    "get":{
      "geometries":1
    }
  }
}

