POST http://localhost:8000/funql
content-type: application/json

//Not Work : Success True But Not Delete

{
  "wants": {
    "model": "Dish",
    "doit":"Delete"
  },
  "details":{
    "set":{
      "_id":"606a9688789486c2405a7986"
    },
    "get":{}
  }
}
