POST http://localhost:8000/funql
content-type: application/json

{
  "wants": {
    "model": "Dish",
    "doit":"Delete"
  },
  "details":{
    "set":{
      "_id":"606bec8451f44cbc149e48a2"
    },
    "get":{}
  }
}
