POST http://localhost:8000/funql
content-type: application/json

{
  "wants": {
      "model": "State",
      "doit":"Update"
  },
  "details":{
    "set":{
      "_id": "6065ce5e0ba75b06e50e1fbb",
      "geometries" : [10,25]
    },
    "get":{}
  }
}