POST http://localhost:8000/funql
content-type: application/json

//Not Work : Success True But Not Delete
{
  "wants": {
      "model": "Table",
      "doit":"Delete"
  },
  "details":{
    "set":{
      "_id":"60472c856a7b353f2dbc81c6"
    },
    "get":{
      "name":1
    }
  }
}

