POST http://localhost:8000/funql
content-type: application/json

{
  "wants": {
      "model": "Table",
      "doit":"Update"
  },
  "details":{
    "set":{
      "_id": "6054463d895e80dc6860ddf1",
      "reservable" : false
    },
    "get":{}
  }
}