POST http://localhost:8000/funql
content-type: application/json
token:eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzI5NzcyNjEuOTMxLCJ1c2Vyc0lkIjoiNjA1NDQ2OTA4OTVlODBkYzY4NjBkZGYyIn0.ZGwnHPfKl0FLUHHR0n2wF3bUQzwquvo_Fl-Kq5R2iA4uJWonoKndJV8rjkHSo6QBdC5bCrQW7VYNiplwWQgM-w

//Not Work : Success True But Not Delete
{
  "wants": {
      "model": "Center",
      "doit":"Delete"
  },
  "details":{
    "set":{
      "_id":"6041d03be197f433c435097b"
    },
    "get":{
      "name":1
    }
  }
}
